import type { AdminStore } from "@/lib/admin/types";

export const adminMockData: AdminStore = {
  users: [
    {
      id: "usr-001",
      name: "Nora Al-Sayed",
      email: "nora@zaffa.com",
      role: "super_admin",
      status: "active",
      lastActive: "2m ago",
      department: "Operations",
    },
    {
      id: "usr-002",
      name: "Khalid Rahman",
      email: "khalid@zaffa.com",
      role: "admin",
      status: "active",
      lastActive: "15m ago",
      department: "Sales",
    },
    {
      id: "usr-003",
      name: "Maha Abdullah",
      email: "maha@zaffa.com",
      role: "manager",
      status: "pending",
      lastActive: "1h ago",
      department: "Content",
    },
  ],
  vendors: [
    {
      id: "ven-001",
      name: "Elysian Events",
      specialty: "Luxury planning",
      location: "Riyadh",
      rating: 4.9,
      priceLevel: "premium",
      status: "approved",
      featured: true,
      bio: "High-touch destination planning for premium weddings.",
    },
    {
      id: "ven-002",
      name: "Nour Studios",
      specialty: "Photography",
      location: "Jeddah",
      rating: 4.8,
      priceLevel: "mid",
      status: "review",
      featured: false,
      bio: "Editorial and candid wedding photography.",
    },
  ],
  bookings: [
    {
      id: "bk-001",
      clientName: "Sara & Omar",
      vendorName: "Elysian Events",
      service: "Full wedding coordination",
      status: "confirmed",
      date: "2026-09-12",
      amount: 18000,
      location: "Abha",
    },
    {
      id: "bk-002",
      clientName: "Layan & Khaled",
      vendorName: "Nour Studios",
      service: "Photography package",
      status: "pending",
      date: "2026-10-03",
      amount: 4200,
      location: "Dammam",
    },
  ],
  categories: [
    {
      id: "cat-001",
      name: "Planning",
      slug: "planning",
      description: "Venue and event strategy services",
      active: true,
    },
    {
      id: "cat-002",
      name: "Photography",
      slug: "photography",
      description: "Capture the wedding story",
      active: true,
    },
  ],
  services: [
    {
      id: "srv-001",
      categoryId: "cat-001",
      name: "Full coordination",
      price: 6500,
      duration: "8 hours",
      featured: true,
    },
    {
      id: "srv-002",
      categoryId: "cat-002",
      name: "Signature shoot",
      price: 3200,
      duration: "6 hours",
      featured: false,
    },
  ],
  contentBlocks: [
    {
      id: "content-001",
      title: "Homepage hero",
      slug: "homepage-hero",
      status: "published",
      updatedAt: "2026-08-01",
    },
    {
      id: "content-002",
      title: "Vendor spotlight",
      slug: "vendor-spotlight",
      status: "draft",
      updatedAt: "2026-07-30",
    },
  ],
  settings: {
    brandName: "Zaffa",
    supportEmail: "support@zaffa.com",
    maintenanceMode: false,
    currency: "SAR",
    locale: "en",
  },
  rolePermissions: [
    {
      role: "super_admin",
      description: "Full access to all platform modules",
      scope: ["users", "vendors", "bookings", "categories", "services", "content", "settings"],
    },
    {
      role: "admin",
      description: "Manage operations and bookings",
      scope: ["vendors", "bookings", "categories", "services", "content"],
    },
    {
      role: "manager",
      description: "Review vendor activity and content",
      scope: ["vendors", "content"],
    },
    {
      role: "viewer",
      description: "View dashboards and reports",
      scope: ["analytics"],
    },
  ],
};
